### ISSUE TITLE
Arm11 Exception when attempting to use BootNTR after playing a GBA game.

### ISSUE THREAD

**Issue by Vermenthruaxx** [PabloMK7/Luma3DS_3GX#1]
**System model:**
New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**
Sys 11.16.0-49U

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap

**Luma3DS version:**
Luma3DS v12.0.1-3gxldr
https://github.com/PabloMK7/Luma3DS_3GX

**Luma3DS configuration/options:**

Screen brightness: 4 (X)

Splash: Off (X)

Splash duration: (N/A)

PIN lock: Off (X)

New 3DS CPU:  Off (X)
--
Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( ) - Not visible in config menu

Disable Arm11 exception handlers: ( ) - Not visible in config menu

Enable Rosalina on SAFE_FIRM: ( ) - Not visible in config menu

--

**Explanation of the issue:**

Using the 3GX Loader fork of Luma3DS to boot NTR CFW, I encounter an Arm11 exception. This happens after a weird interaction with GBA Virtual Console (in this case, Metroid Fusion). Discovered this strange crash attempting to stream Metroid Fusion for a friend. Will be attaching the dump as well.

Quick details at a glance regarding the crash:
Processor - Arm 11 (Core 1)
Exception Type - data abort
Fault status: Translation - Section
Current process: am (0040130000001502)

**Steps to reproduce:**
1. Boot the 3DS
2. Launch Metroid Fusion (potentially any other GBA game as well)
3. When you can, go back to home menu
4. Using BootNTR, attempt to boot into NTR CFW
5. Congrats, you crashed!

**Dump file:**
[arm11 crash dump.zip](https://github.com/PabloMK7/Luma3DS_3GX/files/11299918/arm11.crash.dump.zip)

**Comment by PabloMK7** [comment]
Hello! You cannot stream DS or GBA games with NTR CFW, as the console switches to TWL/GBA mode and shuts down a lot 3DS specific hardware required for NTR CFW to work.

In any case, this is an issue with NTR CFW and not with Luma, so I'm closing this issue. If it becomes problematic (which I doubt because you can just reboot) it will be reopened.
